name: C/C++ CI with Autotools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies on macOS
      run: |
        brew update
        brew install autoconf automake gettext git make

    - name: Run autogen
      run: ./autogen.sh

    - name: Configure
      run: |
        ./configure

    - name: Build
      run: make

    - name: Run checks
      run: make check

    - name: Set commit status
      uses: actions/github-script@v4
      with:
        script: |
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'autotools',
            description: 'Autotools build successful',
            target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          })
